spring:
  datasource:
    url: jdbc:mysql://localhost:3306/student_crud?useSSL=false&serverTimezone=UTC
    username: root
    password: Nikhitha09
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # or create
    show-sql: true